#!/usr/bin/env python3
import datetime as dt
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
STATE = ROOT / ".autodev" / "runtime" / "state.runtime.json"
SNAPSHOT = ROOT / ".autodev" / "runtime" / "roadmap_snapshot.md"


def main() -> int:
    state = {}
    if STATE.exists():
        state = json.loads(STATE.read_text(encoding="ascii"))

    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    content = "\n".join(
        [
            "# Autonomous Roadmap Snapshot",
            "",
            f"- timestamp: {now}",
            f"- completed_cycles: {state.get('completed_cycles', 0)}",
            f"- last_completed_task: {state.get('last_completed_task')}",
            f"- last_commit: {state.get('last_commit')}",
            f"- last_tag: {state.get('last_tag')}",
            "",
            "This file is runtime telemetry generated by feature roadmap lane.",
            "",
        ]
    )
    SNAPSHOT.write_text(content, encoding="ascii")
    print("feature_roadmap_sync: snapshot updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
